### ISSUE TITLE
Bug: wrong "Content-type" header in IPN response

### ISSUE THREAD

**Issue by karer** [wirecard/merchant-documentation-gateway#105]
Hello, I found an issue with IPN.

**Description**

When creating Wirecard Payment Page (WPP) payment request, I set notification format to `application/json-signed`.

Then incoming request:
- Body content is encoded as `x-www-form-urlencoded` (should be `json`)
- Encoding header (`Content-type:`) has value of `application/text` instead of `application/x-www-form-urlencoded`. 
Note: as we SHOULD receive json, this should be `application/json`. But if api doesn't support json response, then just give us correct header to body - form urlencoded :)

**Request code fragment**
```
{
    ...
    notifications: {
        format: "application/json-signed"
    }
}
```

**Comment by mke-wd** [comment]
Hi Kacper Geisheimer! 

Thanks for your info. 

I think that there is an information missing in the documentation. Maybe using
format: "application/json+signed" helps?

If not, let me know and I will futher analyse it. 

BR
Moritz

**Comment by ldz-w** [comment]
no follow up - closing
