### ISSUE TITLE
docs mismatch

### ISSUE THREAD

**Issue by chiefbiiko** [wirecard/merchant-documentation-gateway#425]
was wondering how to include payment methods in the WPP v2 payment session init request looking at [the EPP integration example](https://doc.wirecard.com/IntegrationGuides_WPP_v2.html#PaymentPageSolutions_PPv2_EPP_Integration_Example) -
* the example json looks like 
```json
{
  "payment": {
    "payment-methods": {
      "payment-method": [
        {
          "name": "creditcard"
        }
      ]
    }
  }
}
```
* but the table below states
<img width="714" alt="paymentmethod" src="https://user-images.githubusercontent.com/22937570/81149194-07ef5c80-8f7e-11ea-85d4-f57a484d407c.PNG">

which one is correct?

**Comment by KarinKraus** [comment]
Hi @chiefbiiko - thanks for raising this issue. The sample is correct - sorry for the confusion!
We'll make sure to update the field tables as soon as we can.
